HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = 'deepfakes'
USERNAME = 'root'
PASSWORD = '12345678'

DB_URI = f'mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset=utf8'

SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_ECHO = False

